---
title: Site Mardan Seguros
timezone: America/La_Paz
collections:
  posts:
    title: Posts
    output: true
  servicos:
    title: Serviços
    output: true
    permalink: servicos
  uploads:
    title: Uploads
    output: true
